const productos = [
  {
    id: 174430,
    nombre: "Gloomhaven",
    precio: 159.99,
    img: "./images/174430.webp",
    stock: 2,
    ano: 2017,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 8.79244,
    BGGrank: 1,
    complejidad: 3.8604,
    categoria: ["Strategy Games", "Thematic Games"],
    descripcion:
      "Gloomhaven es un juego de combate táctico con inspiración europea en un mundo persistente. Los jugadores, como aventureros, colaboran para limpiar mazmorras, mejorar habilidades y explorar en una historia que evoluciona según sus decisiones. El juego utiliza un sistema de cartas innovador para acciones, y los jugadores deben gestionar cuidadosamente sus recursos, ya que perderán cartas permanentemente, pudiendo agotarse si no completan los desafíos a tiempo.",
  },
  {
    id: 167791,
    nombre: "Terraforming Mars",
    precio: 65.9,
    img: "./images/167791.webp",
    stock: 2,
    ano: 2016,
    minjug: 1,
    maxjug: 5,
    tiempo: 120,
    raiting: 8.43254,
    BGGrank: 4,
    complejidad: 3.2406,
    categoria: ["Strategy Games"],
    descripcion:
      "En el siglo XXIV, la humanidad comienza a terraformar el planeta Marte. En el juego Terraforming Mars, interpretas el papel de una de las corporaciones patrocinadas por el Gobierno Mundial en la Tierra, compitiendo por puntos de victoria mientras colaboras en el proceso de terraformación. Adquieres cartas de proyectos únicos para mejorar tu producción de recursos y obtener bonificaciones, equilibrando la compra y la activación de cartas. Compites por ubicaciones estratégicas en el tablero y realizas acciones durante fases de generación, avanzando en la infraestructura humana en el sistema solar. El juego concluye cuando los parámetros globales (temperatura, oxígeno y océano) alcanzan sus objetivos, y el ganador se determina por la Puntuación de Terraformación y otros puntos de victoria acumulados.",
  },
  {
    id: 162886,
    nombre: "Spirit Island",
    precio: 70.99,
    img: "./images/162886.webp",
    stock: 2,
    ano: 2017,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 8.34655,
    BGGrank: 13,
    complejidad: 4.01,
    categoria: ["Strategy Games"],
    descripcion:
      "Spirit Island es un juego cooperativo donde los jugadores encarnan espíritus de la tierra con poderes elementales únicos, trabajando juntos para defender su isla de invasores colonizadores. Cada turno, los jugadores eligen estratégicamente cartas de poder, pagando energía para activar habilidades que varían en velocidad y efectividad. Mientras los espíritus crecen en poder y presencia, los invasores avanzan en la isla, construyendo asentamientos y ciudades. La victoria inicial requiere destruir todas las colonias, pero a medida que aterrorizas a los invasores, la victoria se facilita. Sin embargo, la derrota puede llegar si un espíritu es destruido, la corrupción invade la isla o la baraja de invasores se agota antes de lograr la victoria. Con adversarios variados, cada uno con desafíos únicos, Spirit Island ofrece una experiencia desafiante y temática.",
  },
  {
    id: 120677,
    nombre: "Terra Mystica",
    precio: 59.79,
    img: "./images/120677.webp",
    stock: 2,
    ano: 2012,
    minjug: 2,
    maxjug: 5,
    tiempo: 150,
    raiting: 8.14493,
    BGGrank: 16,
    complejidad: 3.964,
    categoria: ["Strategy Games"],
    descripcion:
      "En la tierra de Terra Mystica habitan 14 pueblos diferentes en siete paisajes, y cada grupo está vinculado a su propio entorno hogareño. Para desarrollarse y crecer, deben transformar paisajes vecinos en sus entornos hogareños en competencia con otros grupos. Terra Mystica es un juego de información completa, sin suerte, que recompensa la planificación estratégica. Cada jugador gobierna uno de los 14 grupos, y con sutileza y habilidad, debe tratar de gobernar la mayor área posible y desarrollar las habilidades de su grupo. Hay cuatro cultos religiosos en los que se puede progresar, y cada grupo tiene habilidades especiales. Durante los turnos, los jugadores ejecutan acciones en los recursos disponibles, desarrollan edificaciones y mejoran habilidades, como terraformación y navegación. La proximidad a otros grupos ofrece ventajas, pero también dificulta la expansión en Terra Mystica.",
  },
  {
    id: 266192,
    nombre: "Wingspan",
    precio: 47.69,
    img: "./images/266192.webp",
    stock: 3,
    ano: 2019,
    minjug: 1,
    maxjug: 5,
    tiempo: 70,
    raiting: 8.11403,
    BGGrank: 20,
    complejidad: 2.4194,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "Wingspan es un juego de mesa competitivo de construcción de motores impulsado por cartas, con un peso medio, desarrollado por Stonemaier Games y diseñado por Elizabeth Hargrave. Con más de 170 ilustraciones de aves de Beth Sobel, Natalia Rojas y Ana María Martínez, los jugadores, como entusiastas de las aves, buscan descubrir y atraer las mejores aves a sus reservas naturales. Cada ave permite crear potentes combinaciones en uno de los hábitats del jugador, centrándose en aspectos clave como obtener fichas de comida mediante dados en una torre de dados, poner huevos con miniaturas de huevos de colores y jugar cartas únicas de aves. El ganador es el jugador con más puntos después de 4 rondas.",
  },
  {
    id: 3076,
    nombre: "Puerto Rico",
    precio: 124.93,
    img: "./images/3076.webp",
    stock: 1,
    ano: 2002,
    minjug: 3,
    maxjug: 5,
    tiempo: 150,
    raiting: 7.98894,
    BGGrank: 28,
    complejidad: 3.2797,
    categoria: ["Strategy Games"],
    descripcion:
      "En Puerto Rico, los jugadores asumen el papel de gobernadores coloniales compitiendo por puntos de victoria mediante el envío de mercancías a Europa o la construcción de edificios. Cada jugador gestiona su propio tablero con ciudad, plantaciones y recursos, compartiendo barcos y una casa de comercio. Durante cada ronda, los jugadores eligen roles, como Comerciante o Constructor, realizando acciones asociadas, y el jugador que selecciona el rol obtiene un pequeño beneficio. El juego utiliza un mecanismo de orden de fase variable, y los jugadores ganan puntos por edificios, envíos y edificios grandes. Puerto Rico incorpora estrategia y toma de decisiones en un entorno colonial, con expansiones disponibles para agregar variedad al juego.",
  },
  {
    id: 31260,
    nombre: "Agricola",
    precio: 58.95,
    img: "./images/31260.webp",
    stock: 3,
    ano: 2007,
    minjug: 1,
    maxjug: 5,
    tiempo: 150,
    raiting: 7.94467,
    BGGrank: 31,
    complejidad: 3.6399,
    categoria: ["Strategy Games"],
    descripcion:
      "En Agricola, te conviertes en un granjero que vive en una cabaña de madera con tu cónyuge y poco más. En cada turno, puedes realizar solo dos acciones, una para ti y otra para tu cónyuge, eligiendo entre diversas posibilidades en la granja, como recolectar arcilla, madera o piedra, construir cercas, entre otras. La complejidad del juego varía según el uso de dos tipos principales de cartas: Mejoras Menores y Ocupaciones. En la versión para principiantes, llamada Variante Familiar, estas cartas no se utilizan, pero en el juego avanzado, hay tres niveles de cartas para ambos tipos: Básico, Interactivo y Complejo. Agricola es un juego por turnos con 14 rondas y 6 etapas, con una cosecha al final de cada etapa. Los jugadores deben gestionar recursos, expandir sus casas, alimentar a su familia y planificar estrategias basadas en cartas de ocupación y mejoras menores. La toma de decisiones estratégicas y la adaptabilidad a las acciones de los oponentes son clave para el éxito en Agricola.",
  },
  {
    id: 2651,
    nombre: "Power Grid",
    precio: 44.95,
    img: "./images/2651.webp",
    stock: 2,
    ano: 2004,
    minjug: 2,
    maxjug: 6,
    tiempo: 120,
    raiting: 7.85549,
    BGGrank: 39,
    complejidad: 3.2717,
    categoria: ["Strategy Games"],
    descripcion:
      "Power Grid es la versión actualizada del juego de crayones Funkenschlag, diseñado por Friedemann Friese. A diferencia de la edición original, Power Grid elimina el uso de crayones en la construcción de redes, pero mantiene el dinámico mercado de commodities similar a Crude: The Oil Game y una ronda de subastas intensa que recuerda a The Princes of Florence. El objetivo del juego es suministrar la mayor cantidad de ciudades con energía cuando la red de un jugador alcanza un tamaño predeterminado. En esta nueva edición, los jugadores establecen rutas entre ciudades y compiten en subastas por la compra de plantas de energía para abastecerlas. La estrategia se centra en la gestión eficiente de recursos como carbón, petróleo, basura y uranio, mientras se busca mejorar las plantas para lograr máxima eficiencia y expandir la red a costos competitivos. La constante toma de decisiones estratégicas y las dinámicas subastas hacen de Power Grid un juego desafiante y cautivador.",
  },
  {
    id: 126163,
    nombre: "Tzolk'in: The Mayan Calendar",
    precio: 58.91,
    img: "./images/126163.webp",
    stock: 2,
    ano: 2012,
    minjug: 2,
    maxjug: 4,
    tiempo: 90,
    raiting: 7.90203,
    BGGrank: 40,
    complejidad: 3.6677,
    categoria: ["Strategy Games"],
    descripcion:
      "Tzolkin: The Mayan Calendar introduce un innovador mecanismo de juego mediante la colocación dinámica de trabajadores. En este juego, representando diversas tribus mayas, los jugadores sitúan a sus trabajadores en grandes engranajes interconectados, y a medida que los engranajes giran, los trabajadores se desplazan a diferentes lugares de acción. Durante un turno, los jugadores pueden colocar trabajadores en los lugares visibles más bajos de los engranajes o recoger trabajadores para realizar acciones específicas según su posición. La gestión del tiempo es crucial, ya que las acciones en lugares más avanzados son más valiosas, pero los jugadores no pueden omitir sus turnos y deben equilibrar estratégicamente sus decisiones. El juego culmina después de una revolución completa del engranaje central Tzolkin, ofreciendo múltiples caminos hacia la victoria, como complacer a los dioses con calaveras de cristal o la construcción de templos, brindando a los jugadores una experiencia rica y desafiante.",
  },
  {
    id: 284083,
    nombre: "The Crew: The Quest for Planet Nine",
    precio: 14.99,
    img: "./images/284083.webp",
    stock: 2,
    ano: 2019,
    minjug: 2,
    maxjug: 5,
    tiempo: 20,
    raiting: 8.01935,
    BGGrank: 41,
    complejidad: 1.9939,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "En el juego cooperativo de bazas, The Crew: La Búsqueda de Planeta Nueve, los jugadores encarnan astronautas en una aventura espacial llena de incertidumbres sobre el planeta desconocido. Con más de 50 misiones emocionantes, el desafío radica en superar el juego al cumplir con tareas individuales comunes para cada jugador. La comunicación se vuelve esencial en el equipo para enfrentar las variadas dificultades, pero en el espacio, resulta más complicada de lo esperado. Cada misión aumenta la dificultad, y después de cada una, el juego se puede pausar y reanudar más tarde. En lugar de la cantidad de bazas, lo que cuenta en cada misión son las bazas correctas en el momento adecuado. El equipo logra completar una misión solo si cada jugador tiene éxito en sus tareas individuales. El juego ofrece 50 misiones, con tres misiones adicionales publicadas en la revista spielbox 2/2020.",
  },
  {
    id: 35677,
    nombre: "Le Havre",
    precio: 70.99,
    img: "./images/35677.webp",
    stock: 2,
    ano: 2008,
    minjug: 1,
    maxjug: 5,
    tiempo: 150,
    raiting: 7.86847,
    BGGrank: 47,
    complejidad: 3.7427,
    categoria: ["Strategy Games"],
    descripcion:
      "En Le Havre, cada turno de un jugador se divide en dos partes: en primer lugar, distribuir los bienes recién suministrados en los espacios de oferta y, luego, tomar una acción. Durante la acción, los jugadores pueden elegir tomar todos los bienes de un tipo de un espacio de oferta o utilizar uno de los edificios disponibles. Las acciones de construcción permiten mejorar bienes, venderlos o utilizarlos para construir edificios y barcos. Estos edificios representan tanto una inversión como una fuente de ingresos, ya que se debe pagar una tarifa para usar edificios ajenos. Por otro lado, los barcos son esenciales para proporcionar alimentos y alimentar a los trabajadores. Después de siete turnos, concluye la ronda con una cosecha que puede multiplicar el ganado y el grano de los jugadores, quienes deben asegurarse de alimentar a sus trabajadores. Tras un número predeterminado de rondas, cada jugador realiza una acción final, sumando el valor de sus edificios y barcos a sus reservas de dinero para determinar al ganador, quien haya acumulado la mayor fortuna.",
  },
  {
    id: 230802,
    nombre: "Azul",
    precio: 31.99,
    img: "./images/230802.webp",
    stock: 3,
    ano: 2017,
    minjug: 2,
    maxjug: 4,
    tiempo: 45,
    raiting: 7.82838,
    BGGrank: 50,
    complejidad: 1.7663,
    categoria: ["Abstract Games", "Family Games"],
    descripcion:
      "Azul nos sumerge en la fascinante historia de los azulejos portugueses, inspirados inicialmente por los moros y adoptados con fervor por el rey Manuel I después de quedar cautivado por la belleza de la Alhambra. Como artistas en colocación de azulejos, los jugadores asumen el desafío de embellecer los muros del Palacio Real de Évora. En este juego estratégico, los participantes seleccionan hábilmente azulejos de colores de los proveedores y los disponen en sus tableros de jugador, puntuando según la disposición de estos en la decoración del palacio. Los patrones específicos y la finalización de conjuntos brindan puntos adicionales, mientras que el despilfarro de suministros afecta negativamente la puntuación. Al final, el jugador que haya acumulado la mayor cantidad de puntos se consagra como el ganador, celebrando su habilidad para crear un magnífico mosaico en el Palacio Real de Évora.",
  },
  {
    id: 125153,
    nombre: "The Gallerist",
    precio: 199.95,
    img: "./images/125153.webp",
    stock: 3,
    ano: 2015,
    minjug: 1,
    maxjug: 4,
    tiempo: 150,
    raiting: 8.04333,
    BGGrank: 57,
    complejidad: 4.281,
    categoria: ["Strategy Games"],
    descripcion:
      "En esta era de arte y capitalismo, surge la necesidad de una nueva ocupación: El Galerista. En este juego, asumes el papel de marchante de arte, curador de museo y manager de artistas, llevando a cabo la promoción y fomento de artistas, la compra, exhibición y venta de sus obras de arte, y la construcción de tu reputación internacional. Para tener éxito, debes atraer visitantes de todo el mundo a tu galería, contratando asistentes para ayudarte en la consecución de tus objetivos. La clave para ganar radica en maximizar tu fortuna a través de la gestión eficiente de la galería, atrayendo visitantes, exhibiendo y vendiendo obras de arte, invirtiendo en la promoción de artistas y cumpliendo con diversos objetivos de curador y marchante. Conviértete en un Gallerist de renombre mundial y asegura tu posición en la cima del mundo del arte.",
  },
  {
    id: 68448,
    nombre: "7 Wonders",
    precio: 59.99,
    img: "./images/68448.webp",
    stock: 2,
    ano: 2010,
    minjug: 2,
    maxjug: 7,
    tiempo: 30,
    raiting: 7.75152,
    BGGrank: 61,
    complejidad: 2.329,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "En 7 Wonders, como líder de una de las 7 grandes ciudades del Mundo Antiguo, tu objetivo es reunir recursos, desarrollar rutas comerciales y afirmar tu supremacía militar. A lo largo de tres edades, los jugadores seleccionan cartas de mazos específicos, eligen una y pasan las demás a jugadores adyacentes. Se revelan simultáneamente, pagando recursos, recolectando y interactuando. Con cartas de efectos inmediatos, bonificaciones y mejoras, descuentos y fuerza militar, cada elección afecta estratégicamente. Después de tres edades, el juego concluye, y ganas mediante la construcción de tu ciudad y la erección de una maravilla arquitectónica. Aunque la caja indica de 3-7 jugadores, se incluye una variante oficial para 2 jugadores en las instrucciones. Mantén la atención en los vecinos, ya que las cartas se pasan en ambas direcciones, y demuestra tu habilidad para liderar en este fascinante juego de desarrollo de cartas.",
  },
  {
    id: 229853,
    nombre: "Teotihuacan: City of Gods",
    precio: 49.95,
    img: "./images/229853.webp",
    stock: 3,
    ano: 2018,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.95353,
    BGGrank: 62,
    complejidad: 3.7658,
    categoria: ["Strategy Games"],
    descripcion:
      "En Teotihuacan: City of Gods, viaja en el tiempo a la grandiosa ciudad de Mesoamérica y contempla la gloria y el ocaso de la poderosa civilización precolombina. Estratégicamente, acumula riquezas, obtén el favor de los dioses y conviértete en el constructor de la magnífica Pirámide del Sol. Cada jugador dirige una fuerza de dados obreros que aumentan su fuerza con cada movimiento. En tu turno, desplazas un obrero por un tablero modular, eligiendo una de dos áreas en la casilla de ubicación donde aterrizas: una te ofrece una acción (y una mejora para tu obrero), la otra proporciona un poderoso bono (pero sin mejora). Mientras gestionas tu fuerza laboral y recursos, desarrollas nuevas tecnologías, avanzas en los templos, construyes viviendas y elevas la legendaria Pirámide del Sol en el centro de la ciudad. El juego se desarrolla en tres eras, evaluando los esfuerzos de los jugadores y su capacidad para alimentar a su fuerza laboral. Al acercarse el amanecer de los aztecas, se determina el jugador con más fama como el ganador.",
  },
  {
    id: 244521,
    nombre: "The Quacks of Quedlinburg",
    precio: 39.99,
    img: "./images/244521.webp",
    stock: 1,
    ano: 2018,
    minjug: 2,
    maxjug: 4,
    tiempo: 45,
    raiting: 7.82396,
    BGGrank: 64,
    complejidad: 1.9426,
    categoria: ["Family Games"],
    descripcion:
      "En The Quacks of Quedlinburg, los jugadores son charlatanes o médicos fraudulentos, cada uno creando su propia poción secreta al agregar ingredientes uno a uno. Ten cuidado con lo que añades, ya que un toque demasiado de esto o aquello estropeará toda la mezcla. Cada jugador tiene su propia bolsa de fichas de ingredientes. Durante cada ronda, todos dibujan fichas simultáneamente de sus bolsas y las añaden a sus calderos. Cuanto mayor sea el valor de la ficha, más lejos se coloca en el remolino del caldero, aumentando el valor de la poción. Arriésgate tanto como puedas, pero ¡si añades demasiadas bombas de cereza, tu caldero explotará! Al final de cada ronda, los jugadores ganan puntos de victoria y monedas para gastar en nuevos ingredientes, según lo bien que lograron llenar sus calderos. Pero los jugadores cuyos calderos han explotado deben elegir entre puntos o monedas, ¡no ambos! El jugador con más puntos de victoria al final de nueve rondas gana el juego.",
  },
  {
    id: 161533,
    nombre: "Lisboa",
    precio: 126.95,
    img: "./images/161533.webp",
    stock: 1,
    ano: 2017,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 8.18437,
    BGGrank: 69,
    complejidad: 4.5667,
    categoria: ["Strategy Games"],
    descripcion:
      "Lisboa es un juego que aborda la reconstrucción de la ciudad tras el devastador terremoto de 1755. Ambientado en el contexto histórico, los jugadores, miembros de la nobleza, colaboran con el Marqués de Pombal para reconstruir Lisboa. Cada ronda, planifican negocios en las calles del centro, gestionan influencia, licencias de construcción y permisos comerciales, y buscan favores de personajes importantes. El juego utiliza un mapa real de Lisboa y la economía se impulsa mediante la gestión del tesoro real, ofreciendo una experiencia única en cada partida. El objetivo es acumular la mayor cantidad de pelucas al final del juego, sumergiendo a los jugadores en una fascinante travesía por la reconstrucción de la ciudad tras la catástrofe de 1755.",
  },
  {
    id: 18602,
    nombre: "Caylus",
    precio: 124.99,
    img: "./images/18602.webp",
    stock: 2,
    ano: 2005,
    minjug: 2,
    maxjug: 5,
    tiempo: 150,
    raiting: 7.77011,
    BGGrank: 77,
    complejidad: 3.8034,
    categoria: ["Strategy Games"],
    descripcion:
      "Había una vez en 1289... Para fortalecer las fronteras del Reino de Francia, el rey Felipe el Hermoso decidió construir un nuevo castillo. En ese momento, Caylus era solo un humilde pueblo, pero pronto, trabajadores y artesanos acudirán en masa, atraídos por las grandes perspectivas. Alrededor del lugar de construcción, una ciudad está surgiendo lentamente. Los jugadores encarnan a maestros constructores. Al construir el castillo del rey y desarrollar la ciudad que lo rodea, ganan puntos de prestigio y obtienen el favor del rey. Cuando el castillo esté terminado, el jugador que haya ganado más prestigio será el ganador del juego. En cada turno, los jugadores pagan para colocar a sus trabajadores en varios edificios del pueblo, que les permiten reunir recursos, dinero, construir o mejorar edificios. La elección de los edificios afecta significativamente el curso del juego, ya que determinan las acciones disponibles para todos. A medida que se construyen nuevos edificios, forman una carretera que se aleja del castillo, y no todos pueden usarse cada turno. Los jugadores tienen cierto control sobre qué edificios están activos, influyendo en el marcador del Provost. Este marcador también afecta el movimiento del marcador del Bailiff, que determina el final del juego. En general, si los jugadores construyen muchos edificios y el Provost permite que se usen generosamente, el juego termina más rápidamente.",
  },
  {
    id: 93,
    nombre: "El Grande",
    precio: 56.2,
    img: "./images/93.webp",
    stock: 1,
    ano: 1995,
    minjug: 2,
    maxjug: 5,
    tiempo: 120,
    raiting: 7.75385,
    BGGrank: 79,
    complejidad: 3.053,
    categoria: ["Strategy Games"],
    descripcion:
      "En este galardonado juego, los jugadores asumen el papel de Grandes en la España medieval. El poder del rey está debilitándose, y estos poderosos señores compiten por el control de diversas regiones. Para lograrlo, reclutas caballeros en tu corte y los mueves al tablero para ayudar a tomar el control de las regiones. Después de cada tercer turno, se puntúan las regiones, y después del noveno turno, el jugador con más puntos es el ganador. En cada uno de los nueve turnos, seleccionas una de tus 13 cartas de poder para determinar el orden de turno y la cantidad de caballeros que puedes mover de las provincias (suministro general) a tu corte (suministro personal). Luego, seleccionas una de las cinco cartas de acción que permiten variaciones en las reglas y oportunidades adicionales de puntuación, además de determinar cuántos caballeros mover a una o más regiones en el tablero (o al castillo, una torre secreta). El objetivo es tener la mayoría de caballeros en tantas regiones (y el castillo) como sea posible durante una ronda de puntuación, siguiendo reglas específicas para cada región.",
  },
  {
    id: 42,
    nombre: "Tigris & Euphrates",
    precio: 120,
    img: "./images/42.webp",
    stock: 3,
    ano: 1997,
    minjug: 2,
    maxjug: 4,
    tiempo: 90,
    raiting: 7.69674,
    BGGrank: 92,
    complejidad: 3.5102,
    categoria: ["Strategy Games"],
    descripcion:
      "En Tigris & Éufrates, considerado la obra maestra de Reiner Knizia, los jugadores construyen civilizaciones en el antiguo creciente fértil mediante la colocación de losetas. Cada jugador tiene cuatro líderes diferentes: agricultura, comercio, religión y gobierno, utilizados para acumular puntos de victoria en esas categorías. Sin embargo, al final del juego, la puntuación se basa en la categoría más débil, fomentando la diversificación. Los conflictos surgen cuando las civilizaciones se conectan en el tablero, con solo un líder de cada tipo sobreviviendo. Además, la expansión de zigurat agrega un monumento especial y reglas avanzadas. Tigris & Éufrates es parte de la trilogía de colocación de losetas de Knizia y se destaca por su estrategia y profundidad táctica.",
  },
  {
    id: 203993,
    nombre: "Lorenzo il Magnifico",
    precio: 49.95,
    img: "./images/203993.webp",
    stock: 2,
    ano: 2016,
    minjug: 2,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.89058,
    BGGrank: 96,
    complejidad: 3.2796,
    categoria: ["Strategy Games"],
    descripcion:
      "En Lorenzo il Magnifico, cada jugador asume el papel del jefe de una familia noble durante el Renacimiento italiano, compitiendo por obtener más prestigio y fama, es decir, puntos de victoria (PV), que los demás. Para lograrlo, envías a los miembros de tu familia a diferentes áreas de la ciudad para conseguir logros. En un lugar obtienen recursos, en otro cartas de desarrollo que representan territorios conquistados, edificios patrocinados, personajes influenciados o empresas alentadas. Los miembros de la familia no son idénticos; al principio de cada ronda, lanzas tres dados para determinar su valor y debes elegir sabiamente dónde enviar a los más valiosos. Puedes ganar PV de varias maneras y debes prestar atención a tus relaciones con la Iglesia. El juego se divide en tres períodos, cada uno compuesto por dos rondas, y al final de cada período, los jugadores deben mostrar su fe. Después de seis rondas, calculas tu puntuación final, y el jugador con más PV gana.",
  },
  {
    id: 30549,
    nombre: "Pandemic",
    precio: 31.6,
    img: "./images/30549.webp",
    stock: 3,
    ano: 2008,
    minjug: 2,
    maxjug: 4,
    tiempo: 45,
    raiting: 7.60608,
    BGGrank: 99,
    complejidad: 2.4115,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "En Pandemic, varias enfermedades virulentas han estallado simultáneamente en todo el mundo, y los jugadores asumen el papel de especialistas en la lucha contra enfermedades. Su misión es tratar los focos de enfermedades mientras investigan curas para cuatro plagas antes de que se salgan de control. El tablero del juego representa varios centros de población en la Tierra, y en cada turno, un jugador puede realizar hasta cuatro acciones para viajar entre ciudades, tratar a las poblaciones infectadas, descubrir una cura o construir una estación de investigación. Un mazo de cartas proporciona a los jugadores estas habilidades, pero hay cartas de Epidemia que aceleran e intensifican la actividad de las enfermedades. Los jugadores deben planificar estrategias que se ajusten a las fortalezas de sus especialistas para vencer las enfermedades. Si una o más enfermedades se propagan sin control o si pasa demasiado tiempo, todos los jugadores pierden; si curan las cuatro enfermedades, todos ganan. La edición de 2013 de Pandemic incluye dos personajes nuevos: el Planificador de Contingencias y el Especialista en Cuarentena. Pandemic es el primer juego en la serie Pandemic.",
  },
  {
    id: 281259,
    nombre: "The Isle of Cats",
    precio: 34.9,
    img: "./images/281259.webp",
    stock: 2,
    ano: 2019,
    minjug: 1,
    maxjug: 4,
    tiempo: 90,
    raiting: 8.03779,
    BGGrank: 108,
    complejidad: 2.3235,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "The Isle of Cats es un juego de mesa competitivo donde los jugadores, como ciudadanos de Squalls End, emprenden una misión de rescate en The Isle of Cats para salvar la mayor cantidad de gatos posible antes de la llegada del malvado Lord Vesh. Representados por fichas únicas, los gatos pertenecen a diferentes familias, y los jugadores deben colocarlos estratégicamente en sus barcos, procurando mantener a las familias unidas. A través de la exploración de la isla mediante la elección de cartas, el rescate de gatos, la búsqueda de tesoros, la amistad con Oshax y el estudio de lecciones antiguas, los jugadores gestionan recursos y obtienen puntos. Cada lección recolectada proporciona una forma única de puntuar, y el objetivo es completar lecciones, llenar el barco y mantener a las familias de gatos unidas para acumular la mayor cantidad de puntos posible en cinco rondas y ganar el juego.",
  },
  {
    id: 161970,
    nombre: "Alchemists",
    precio: 59.95,
    img: "./images/161970.webp",
    stock: 2,
    ano: 2014,
    minjug: 2,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.67407,
    BGGrank: 110,
    complejidad: 3.8993,
    categoria: ["Strategy Games"],
    descripcion:
      "En Alchemists, de dos a cuatro aspirantes a alquimistas compiten por descubrir los secretos de su arte místico, ganando puntos de varias maneras, especialmente al publicar teorías correctas. El juego consta de seis rondas en las que los jugadores eligen el orden de juego, declaran acciones mediante cubos en diferentes espacios y obtienen conocimientos al mezclar ingredientes, probando resultados con una aplicación. Los jugadores también pueden comprar artefactos y vender pociones, pero el objetivo final es ganar respeto mediante la publicación de teorías correctas y convertir la reputación en puntos. Después de seis rondas y una exhibición final, los jugadores obtienen puntos por artefactos y subvenciones, y se revelan los secretos de la alquimia, ganando o perdiendo puntos según la corrección de sus teorías. El jugador con más puntos al final gana.",
  },
  {
    id: 262712,
    nombre: "Res Arcana",
    precio: 37.99,
    img: "./images/262712.webp",
    stock: 1,
    ano: 2019,
    minjug: 2,
    maxjug: 4,
    tiempo: 60,
    raiting: 7.8017,
    BGGrank: 118,
    complejidad: 2.5923,
    categoria: ["Strategy Games"],
    descripcion:
      "En Res Arcana, los jugadores se sumergen en un mundo de magia donde las esencias de Vida, Muerte, Elan, Calma y Oro impulsan el arte de la magia. Cada jugador elige un mago, recoge esencias, crea artefactos únicos y los utiliza para invocar dragones, conquistar lugares de poder y lograr la victoria. El juego consta generalmente de 4-6 rondas, donde los jugadores realizan acciones como recolectar esencias, colocar artefactos, reclamar monumentos o Lugares de Poder, y descartar cartas para obtener Oro o esencias. El objetivo es acumular puntos de victoria, y el juego ofrece estrategias diversas para alcanzar el triunfo.",
  },
  {
    id: 163068,
    nombre: "Trickerion: Legends of Illusion",
    precio: 58.95,
    img: "./images/163068.webp",
    stock: 1,
    ano: 2015,
    minjug: 2,
    maxjug: 4,
    tiempo: 180,
    raiting: 7.89472,
    BGGrank: 128,
    complejidad: 4.1996,
    categoria: ["Strategy Games"],
    descripcion:
      "Trickerion es un juego competitivo de estrategia Euro-style ambientado en un mundo ficticio inspirado en la vida y cultura urbana de finales del siglo XIX, condimentado con un toque de lo sobrenatural. Los jugadores asumen los roles de ilusionistas de escenario rivales, cada uno con sus propias fortalezas y características, que buscan fortuna y fama en una competencia organizada por un legendario mago. Utilizando mecanismos de colocación de trabajadores y selección de acciones simultáneas, los ilusionistas y sus equipos obtienen planos y componentes para trucos de magia cada vez más complejos, expanden su equipo y realizan actuaciones en diferentes ubicaciones de la ciudad en el tablero principal. El juego ofrece una amplia variedad de trucos, habilidades de personajes y cartas de asignación especial, con el objetivo de acumular puntos de fama y monedas. Trickerion promete una experiencia estratégica rica con múltiples caminos hacia la victoria y la posibilidad de expandirse con módulos opcionales para mayor profundidad.",
  },
  {
    id: 54043,
    nombre: "Jaipur",
    precio: 20.47,
    img: "./images/54043.webp",
    stock: 1,
    ano: 2009,
    minjug: 2,
    maxjug: 2,
    tiempo: 30,
    raiting: 7.50944,
    BGGrank: 138,
    complejidad: 1.4904,
    categoria: ["Family Games"],
    descripcion:
      "En Jaipur, eres uno de los dos comerciantes más poderosos en la ciudad de Jaipur, la capital de Rajasthan, pero eso no es suficiente porque solo el comerciante con dos sellos de excelencia tendrá el privilegio de ser invitado a la corte del Maharajá. Por lo tanto, tendrás que hacerlo mejor que tu competidor directo comprando, intercambiando y vendiendo a mejores precios, todo mientras cuidas tus manadas de camellos. Jaipur es un juego de cartas rápido, una mezcla de táctica, riesgo y suerte. En tu turno, puedes tomar o vender cartas. Si tomas cartas, debes elegir entre tomar todos los camellos, tomar una carta del mercado o intercambiar entre 2 y 5 cartas entre el mercado y tus cartas. Si vendes cartas, solo puedes vender un tipo de bien y recibes tantas fichas por ese bien como cartas vendiste. Los valores de las fichas disminuyen a medida que avanza el juego, ¡así que más vale que te des prisa! Por otro lado, recibes recompensas cada vez más altas por vender tres, cuatro o cinco cartas del mismo bien a la vez, ¡así que más vale que esperes! No puedes vender camellos, pero son fundamentales para el comercio y también valen algo al final de la ronda, a veces lo suficiente para asegurarte la victoria, así que debes usarlos con inteligencia.",
  },
  {
    id: 146508,
    nombre: "T.I.M.E Stories",
    precio: 40.76,
    img: "./images/146508.webp",
    stock: 3,
    ano: 2015,
    minjug: 2,
    maxjug: 4,
    tiempo: 90,
    raiting: 7.55033,
    BGGrank: 145,
    complejidad: 2.6085,
    categoria: ["Thematic Games"],
    descripcion:
      "En T.I.M.E Stories, los jugadores asumen el papel de agentes temporales de la Agencia T.I.M.E, embarcándose en misiones para prevenir fallas temporales. El juego combina elementos narrativos y de estrategia, donde cada jugador explora escenarios únicos, resuelve acertijos y supera desafíos en diferentes líneas temporales. Con una mecánica de decksploration, los jugadores utilizan Unidades Temporales para realizar acciones, con el objetivo de completar la misión en el menor número de intentos posibles. El componente narrativo se mezcla con elementos tácticos, y la posibilidad de retroceder en el tiempo agrega una capa estratégica única. Con una amplia variedad de escenarios y la capacidad de personalizar roles, T.I.M.E Stories ofrece una experiencia inmersiva donde la colaboración y la toma de decisiones estratégicas son clave para el éxito temporal.",
  },
  {
    id: 148228,
    nombre: "Splendor",
    precio: 40.22,
    img: "./images/148228.webp",
    stock: 1,
    ano: 2014,
    minjug: 2,
    maxjug: 4,
    tiempo: 30,
    raiting: 7.45037,
    BGGrank: 166,
    complejidad: 1.7986,
    categoria: ["Family Games"],
    descripcion:
      "Splendor es un juego de recolección de fichas y desarrollo de cartas en el Renacimiento. Los jugadores son comerciantes que buscan comprar minas de gemas, medios de transporte y tiendas para adquirir la mayor cantidad de puntos de prestigio. En tu turno, puedes recolectar fichas, comprar y construir cartas, o reservar una carta. Recolectar fichas te permite tomar tres fichas diferentes o dos fichas del mismo tipo. Comprar una carta implica pagar su precio en fichas y agregarla a tu área de juego. Reservar una carta te permite colocarla frente a ti para construirla más tarde, otorgándote también una ficha de comodín. Las cartas compradas aumentan tu riqueza al proporcionar bonificaciones permanentes, y algunas otorgan puntos de prestigio. El objetivo es alcanzar 15 puntos de prestigio antes que tus oponentes para ganar el juego.",
  },
  {
    id: 146886,
    nombre: "La Granja",
    precio: 35,
    img: "./images/146886.webp",
    stock: 2,
    ano: 2014,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.67286,
    BGGrank: 168,
    complejidad: 3.5835,
    categoria: ["Strategy Games"],
    descripcion:
      "En La Granja, los jugadores controlan pequeñas granjas junto al estanque de Alpich cerca del pueblo de Esporles en la isla de Mallorca. A lo largo de 6 rondas de juego, los jugadores expandirán sus granjas añadiendo campos, extensiones, carros de mercado y ayudantes. Ganarán puntos de victoria entregando bienes al pueblo de Esporles. Es esencial observar las acciones de los demás jugadores, manipular el orden de turno y ajustar la estrategia según los dados y las cartas. La Granja es un juego fascinante que requiere una planificación cuidadosa, donde la sincronización y la rapidez son cruciales. Sin embargo, los jugadores exitosos deben lidiar con la incertidumbre de los eventos durante el juego. El jugador que haya obtenido más puntos de victoria al final del juego se convierte en el ganador y nuevo propietario de la finca La Granja.",
  },
  {
    id: 9209,
    nombre: "Ticket to Ride",
    precio: 43.97,
    img: "./images/9209.webp",
    stock: 2,
    ano: 2004,
    minjug: 2,
    maxjug: 5,
    tiempo: 60,
    raiting: 7.42458,
    BGGrank: 174,
    complejidad: 1.8487,
    categoria: ["Family Games"],
    descripcion:
      "En Ticket to Ride, un juego de alta accesibilidad con reglas sencillas, los jugadores compiten por completar rutas ferroviarias en América del Norte, utilizando cartas de diferentes tipos de vagones de tren. Cuanto más extensas sean las rutas, más puntos obtendrán, y puntos adicionales se otorgan por cumplir con Billetes de Destino que conectan ciudades distantes. Con una jugabilidad fácil de aprender y componentes de alta calidad, Ticket to Ride ha ganado reconocimiento como un juego de entrada, siendo lo suficientemente simple para nuevos jugadores pero lo bastante emocionante para mantener su interés.",
  },
  {
    id: 822,
    nombre: "Carcassonne",
    precio: 22.67,
    img: "./images/822.webp",
    stock: 1,
    ano: 2000,
    minjug: 2,
    maxjug: 5,
    tiempo: 45,
    raiting: 7.41951,
    BGGrank: 178,
    complejidad: 1.9126,
    categoria: ["Family Games"],
    descripcion:
      "Carcassonne es un juego de colocación de losetas en el que los jugadores dibujan y colocan una loseta con un fragmento del paisaje del sur de Francia. Las losetas pueden presentar una ciudad, una carretera, un claustro, campos o una combinación de estos elementos, y deben colocarse junto a las losetas ya jugadas, de manera que las ciudades estén conectadas con ciudades, las carreteras con carreteras, etc. Después de colocar una loseta, el jugador puede decidir colocar uno de sus peones en una de las áreas de la loseta: en la ciudad como caballero, en la carretera como bandido, en un claustro como monje o en el campo como granjero. Cuando esa área está completa, el peón puntúa puntos para su dueño. Carcassonne presenta decisiones estratégicas, como ¿Vale la pena poner mi último peón aquí? o ¿Debería expandir mi ciudad con esta loseta, o debería colocarla cerca de mi oponente para dificultar la finalización de su proyecto y anotar puntos? A pesar de las múltiples opciones, las rondas avanzan rápidamente, convirtiéndolo en el primer juego de la serie Carcassonne.",
  },
  {
    id: 555,
    nombre: "The Princes of Florence",
    precio: 65,
    img: "./images/555.webp",
    stock: 2,
    ano: 2000,
    minjug: 2,
    maxjug: 5,
    tiempo: 100,
    raiting: 7.53286,
    BGGrank: 184,
    complejidad: 3.2503,
    categoria: ["Strategy Games"],
    descripcion:
      "En The Princes of Florence, los jugadores se sumergen en la atrayente tarea de atraer artistas y eruditos a sus palacios mientras compiten por convertirse en la familia más prestigiosa de Florencia. A lo largo de siete rondas, buscan acumular puntos de diversas maneras, centrándose principalmente en jugar cartas de profesiones para generar puntos de trabajo, los cuales se pueden canjear por dinero o puntos de victoria. Las profesiones, que incluyen astrónomos, organistas y arquitectos, son atraídas por combinaciones específicas de edificios, características del paisaje y libertades sociales, y los jugadores compiten por estos elementos mediante subastas. A medida que avanza el juego, el umbral mínimo de puntos de trabajo necesario para convertirlos aumenta en cada ronda, lo que agrega un componente estratégico adicional a medida que los jugadores planifican y ajustan sus estrategias para alcanzar la victoria.",
  },
  {
    id: 192291,
    nombre: "Sushi Go Party!",
    precio: 19.99,
    img: "./images/192291.webp",
    stock: 3,
    ano: 2016,
    minjug: 2,
    maxjug: 8,
    tiempo: 20,
    raiting: 7.46478,
    BGGrank: 188,
    complejidad: 1.3196,
    categoria: ["Family Games"],
    descripcion:
      "Sushi Go Party! amplía Sushi Go! con un surtido de mega maki, super sashimi y edamame interminable. Aún ganas puntos al elegir combinaciones ganadoras de sushi, pero ahora puedes personalizar cada juego eligiendo a la carta de un menú con más de veinte platos deliciosos. Además, hasta ocho jugadores pueden unirse al festín de sushi. ¡Que comiencen los buenos momentos!",
  },
  {
    id: 20551,
    nombre: "Shogun",
    precio: 64,
    img: "./images/20551.webp",
    stock: 2,
    ano: 2006,
    minjug: 3,
    maxjug: 5,
    tiempo: 120,
    raiting: 7.53973,
    BGGrank: 196,
    complejidad: 3.3737,
    categoria: ["Strategy Games"],
    descripcion:
      "En Shogun, ambientado en el Japón del Período Sengoku, cada jugador encarna a un destacado Daimyo, dirigiendo sus tropas para conquistar las provincias de las islas japonesas. Con 10 acciones posibles, los jugadores eligen estratégicamente cómo desarrollar sus reinos y obtener puntos. Durante las rondas, las batallas entre ejércitos se resuelven de manera única con la Cube Tower, donde los cubos que caen indican el resultado. La posesión de provincias, templos y castillos se traduce en puntos al final del juego, y el Daimyo con la puntuación más alta se convierte en el SHOGUN. Con un sistema basado en Wallenstein, Shogun ofrece una experiencia única con componentes sin dependencia de idioma y reglas disponibles en cinco idiomas diferentes.",
  },
  {
    id: 108745,
    nombre: "Seasons",
    precio: 72.66,
    img: "./images/108745.webp",
    stock: 1,
    ano: 2012,
    minjug: 2,
    maxjug: 4,
    tiempo: 60,
    raiting: 7.4053,
    BGGrank: 212,
    complejidad: 2.7699,
    categoria: ["Strategy Games"],
    descripcion:
      "Seasons es un juego táctico de cartas y dados que se desarrolla en dos fases: la primera fase, llamada Preludio, consiste en un draft de cartas, donde el objetivo es establecer un mazo de 9 cartas para la fase principal del juego y definir una estrategia. Una vez completado el Preludio, los jugadores dividen sus 9 cartas en 3 paquetes de 3 cartas cada uno. Comienzan la segunda fase del juego con el primer paquete de tres cartas y, a medida que avanza el juego, reciben los otros dos paquetes de tres cartas. Luego viene el Torneo, donde al principio de cada ronda, un jugador lanza los dados de las estaciones (dados = número de jugadores +1). Estos dados ofrecen diversas acciones a los jugadores, como aumentar su indicador (número máximo de cartas que pueden tener en juego), recolectar energía (agua, tierra, fuego, aire) para pagar el costo de las cartas de poder, cristalizar la energía para recolectar cristales o robar nuevas cartas. Cada jugador elige solo un dado por turno, y el dado no elegido por nadie determina cuántos campos avanzará la pista de tiempo. Al final del juego, se suman los cristales con los puntos de victoria otorgados por las cartas, y el jugador con la puntuación más alta gana.",
  },
  {
    id: 92828,
    nombre: "Dixit: Odyssey",
    precio: 20.99,
    img: "./images/92828.webp",
    stock: 2,
    ano: 2011,
    minjug: 3,
    maxjug: 12,
    tiempo: 30,
    raiting: 7.45168,
    BGGrank: 215,
    complejidad: 1.1899,
    categoria: ["Party Games"],
    descripcion:
      "Dixit Odyssey es una experiencia encantadora que combina creatividad y conexión entre jugadores. En cada turno, el narrador desencadena la imaginación al dar pistas sutiles sobre una carta, mientras que los demás jugadores seleccionan la carta que mejor encaje con la pista. La diversidad de ilustraciones evoca interpretaciones únicas, y la mecánica de voto agrega emoción a medida que todos intentan descifrar la carta del narrador. Esta versión autónoma se destaca con sus 84 cartas inéditas, cada una una obra de arte única, y ofrece la posibilidad de expansión con variantes de juego. Con su atractivo artístico y su capacidad para involucrar a jugadores de todas las edades, Dixit Odyssey es una opción cautivadora para quienes buscan una experiencia lúdica y creativa.",
  },
  {
    id: 144344,
    nombre: "Rococo",
    precio: 95,
    img: "./images/144344.webp",
    stock: 2,
    ano: 2013,
    minjug: 2,
    maxjug: 5,
    tiempo: 120,
    raiting: 7.58378,
    BGGrank: 227,
    complejidad: 3.0945,
    categoria: ["Strategy Games"],
    descripcion:
      "Rococo transporta a los jugadores al esplendor de la era Rococó durante el reinado de Luis XV, donde la organización de suntuosos bailes está de moda. Los jugadores asumen el papel de modistas que no solo se dedican a crear elegantes vestimentas, sino que también se enfrentan al desafío de gestionar el baile más prestigioso de la época. En este juego de estilo euro, los jugadores utilizan cartas de empleados para realizar diversas acciones, como contratar nuevos empleados, comprar recursos, fabricar abrigos y vestidos, o invertir en la decoración del baile. La elección estratégica de empleados es crucial, ya que cada uno otorga beneficios únicos que generan puntos de prestigio. Después de siete rondas, el juego culmina en el gran baile, seguido de una puntuación final, donde se otorgan puntos de prestigio por bonificaciones de empleados, prendas alquiladas y decoraciones financiadas. Rococo ofrece una experiencia inmersiva que combina la gestión inteligente con la creatividad en la alta sociedad del Rococó.",
  },
  {
    id: 286096,
    nombre: "Tapestry",
    precio: 70.97,
    img: "./images/286096.webp",
    stock: 3,
    ano: 2019,
    minjug: 1,
    maxjug: 5,
    tiempo: 120,
    raiting: 7.48614,
    BGGrank: 233,
    complejidad: 2.8784,
    categoria: ["Strategy Games"],
    descripcion:
      "Tapestry es un juego de mesa estratégico diseñado por Jamey Stegmaier, que ofrece una experiencia de juego de dos horas para 1-5 jugadores. Los jugadores se embarcan en un viaje para crear una civilización única, comenzando desde los albores de la humanidad y avanzando hacia el futuro. El juego gira en torno a avanzar en cuatro pistas distintas: ciencia, tecnología, exploración y militar, cada una proporcionando diversos beneficios. A medida que los jugadores desarrollan sus ingresos, construyen sus ciudades capitales y aprovechan habilidades asimétricas individuales, también ganan puntos de victoria y adquieren cartas de tapiz que narran la historia en evolución de su civilización. Las elecciones dinámicas y los caminos diversos hacen de Tapestry una experiencia de juego envolvente e inmersiva.",
  },
  {
    id: 227789,
    nombre: "Heaven & Ale",
    precio: 129.99,
    img: "./images/227789.webp",
    stock: 2,
    ano: 2017,
    minjug: 2,
    maxjug: 4,
    tiempo: 90,
    raiting: 7.58336,
    BGGrank: 268,
    complejidad: 3.2435,
    categoria: ["Strategy Games"],
    descripcion:
      "Heaven & Ale te sitúa al frente de un antiguo monasterio y su cervecería, desafiándote a elaborar la mejor cerveza bajo el cielo azul de Dios. La destreza en la sincronización se vuelve esencial para obtener óptimos resultados en la producción. Tu tarea incluye proveer al jardín del monasterio con recursos fértiles y garantizar la cantidad adecuada de monjes para ayudar en la cosecha. Además, debes tener en cuenta la presencia del maestro cervecero, siempre listo y entusiasmado por perfeccionar cada barril. A medida que compites con otros jugadores, el juego plantea un delicado equilibrio entre mejorar el jardín monástico y recolectar los recursos necesarios para llenar tus barriles, desafiando tu capacidad para mantener la calma y convertirte en el ganador de la carrera por la mejor cerveza.",
  },
  {
    id: 129622,
    nombre: "Love Letter",
    precio: 33.73,
    img: "./images/129622.webp",
    stock: 2,
    ano: 2012,
    minjug: 2,
    maxjug: 4,
    tiempo: 20,
    raiting: 7.23461,
    BGGrank: 284,
    complejidad: 1.1922,
    categoria: ["Family Games"],
    descripcion:
      "En Love Letter, todos los jóvenes elegibles buscan cortejar a la princesa de Tempest, quien se ha encerrado en el palacio, y los jugadores deben depender de otros para entregar sus cartas románticas. El juego, diseñado para 2-4 jugadores, combina riesgo, deducción y suerte. El objetivo es que tu carta de amor llegue a manos de la Princesa Annette mientras intentas evitar las cartas de pretendientes competidores. Con un mazo de solo dieciséis cartas, cada jugador comienza con una sola carta en mano, retirándose una carta del juego. En cada turno, se roba una carta y se juega una carta, buscando exponer a otros y eliminarlos del juego. Cartas poderosas generan ventajas tempranas pero te convierten en blanco, mientras depender de cartas más débiles por demasiado tiempo podría resultar en que tu carta sea arrojada al fuego.",
  },
  {
    id: 9217,
    nombre: "Saint Petersburg",
    precio: 26.77,
    img: "./images/9217.webp",
    stock: 1,
    ano: 2004,
    minjug: 2,
    maxjug: 4,
    tiempo: 60,
    raiting: 7.29935,
    BGGrank: 302,
    complejidad: 2.4689,
    categoria: ["Strategy Games"],
    descripcion:
      "El 16 de mayo de 1703, el zar Pedro colocó la primera piedra del primer edificio en San Petersburgo. Rápidamente, se añadieron edificios gloriosos, siempre en expansión, para que la nobleza (que otorga puntos de victoria) desee mudarse. Pero para lograr esto, se necesitan comerciantes que puedan proporcionar los rublos necesarios, o la gloria se desvanece. La competencia tampoco está dormida y a veces puede robar una carta deseada justo debajo de tus narices. San Petersburgo cuenta con un tablero para contabilizar los puntos de victoria y establecer los cuatro tipos de cartas. Son las cartas en sí mismas las que los jugadores necesitan coleccionar. En cada ronda, con la cantidad de rondas dependiendo del número de jugadores y la aleatoriedad de la disponibilidad de cartas, los jugadores primero pagan por ARTESANOS que proporcionan dinero para compras posteriores; luego, EDIFICIOS para obtener puntos; luego, ARISTÓCRATAS, necesarios para dinero, puntos y puntuación al final del juego; y finalmente, cartas únicas de las tres categorías que otorgan beneficios mayores. Durante las primeras rondas, los jugadores nunca tienen suficiente dinero para comprar todas las cartas que desean. Durante las rondas posteriores, tienen mucho dinero, pero las cartas que les gustaría comprar pueden haber llegado y desaparecido...",
  },
  {
    id: 50,
    nombre: "Lost Cities",
    precio: 24.41,
    img: "./images/50.webp",
    stock: 2,
    ano: 1999,
    minjug: 2,
    maxjug: 2,
    tiempo: 30,
    raiting: 7.17753,
    BGGrank: 323,
    complejidad: 1.4959,
    categoria: ["Family Games"],
    descripcion:
      "Lost Cities es un juego de cartas diseñado para dos jugadores en el que los participantes buscan ganar puntos mediante la realización de expediciones arqueológicas rentables a diferentes sitios representados por cartas de colores. En cada turno, los jugadores deben jugar una carta en orden ascendente en una expedición o descartarla en el montón de descartes adecuado y luego robar una carta. Las cartas jugadas en las expediciones suman puntos según su rango, mientras que los apretones de manos actúan como multiplicadores. El juego desafía a los jugadores a equilibrar sus expediciones y estrategias para obtener la máxima puntuación, convirtiéndolo en una experiencia dinámica y táctica.",
  },
  {
    id: 15987,
    nombre: "Arkham Horror",
    precio: 39.6,
    img: "./images/15987.webp",
    stock: 3,
    ano: 2005,
    minjug: 1,
    maxjug: 8,
    tiempo: 240,
    raiting: 7.25617,
    BGGrank: 333,
    complejidad: 3.577,
    categoria: ["Thematic Games"],
    descripcion:
      "En el año 1926, en pleno apogeo de los Rugientes Años Veinte, las flappers bailan hasta el amanecer en ahumados speakeasies, bebiendo alcohol suministrado por contrabandistas y la mafia. Es una celebración para poner fin a todas las celebraciones en medio de la resaca de la guerra para poner fin a todas las guerras. Sin embargo, una sombra oscura crece en la ciudad de Arkham. Entidades alienígenas conocidas como los Antiguos acechan en el vacío más allá del espacio y el tiempo, retorciéndose en las puertas entre mundos. Estas puertas han comenzado a abrirse y deben cerrarse antes de que los Antiguos conviertan nuestro mundo en su dominio arruinado. Solo unos pocos investigadores se oponen al Horror de Arkham. ¿Prevalecerán? Arkham Horror es un juego de aventuras cooperativo con temática en el Mito de Cthulhu de H.P. Lovecraft. Los jugadores eligen entre 16 investigadores y recorren las calles de Arkham. Antes del juego, se elige uno de los ocho Antiguos, y depende de los investigadores evitar que se abra paso a nuestro mundo. A lo largo del juego, los jugadores mejorarán a sus personajes adquiriendo habilidades, aliados, objetos, armas y hechizos. Depende de los jugadores limpiar las calles de Arkham luchando contra diferentes tipos de monstruos, pero su objetivo principal es cerrar las puertas a otras dimensiones que se están abriendo alrededor de la ciudad. Con demasiadas puertas abiertas, el Antiguo se despierta y los jugadores solo tienen una última oportunidad para salvar al mundo: ¡derrotar al Antiguo en combate!",
  },
  {
    id: 98778,
    nombre: "Hanabi",
    precio: 10.51,
    img: "./images/98778.webp",
    stock: 3,
    ano: 2010,
    minjug: 2,
    maxjug: 5,
    tiempo: 25,
    raiting: 7.08413,
    BGGrank: 393,
    complejidad: 1.7015,
    categoria: ["Family Games"],
    descripcion:
      "Hanabi es un juego de cartas cooperativo donde los jugadores buscan crear el espectáculo perfecto de fuegos artificiales colocando las cartas en la mesa en el orden correcto. La baraja incluye cinco colores diferentes de cartas numeradas del 1 al 5 en cada color, y los jugadores trabajan juntos para ordenarlas correctamente. El desafío radica en que los jugadores sostienen sus cartas de manera que solo son visibles para los demás, y para ayudar a sus compañeros a jugar una carta, deben dar pistas sobre los números o colores de sus cartas. El objetivo es evitar errores y completar el espectáculo de fuegos artificiales antes de quedarse sin cartas.",
  },
  {
    id: 13,
    nombre: "Catan",
    precio: 43.97,
    img: "./images/13.webp",
    stock: 1,
    ano: 1995,
    minjug: 3,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.15261,
    BGGrank: 395,
    complejidad: 2.3213,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "En CATAN, los jugadores compiten por ser la fuerza dominante en la isla de Catan construyendo asentamientos, ciudades y carreteras. En cada turno, se lanzan dados para determinar qué recursos produce la isla, y los jugadores construyen utilizando recursos como lana, trigo, madera, ladrillo y mineral. La disposición inicial implica colocar azulejos hexagonales grandes de manera aleatoria en forma de panal y rodearlos con azulejos de agua que contienen puertos de intercambio. Cada jugador recibe dos asentamientos y carreteras, colocándolos en las intersecciones y bordes de los azulejos de recursos. Se acumulan puntos construyendo asentamientos y ciudades, teniendo la carretera más larga y el ejército más grande, y reuniendo ciertas cartas de desarrollo que otorgan puntos de victoria. Cuando un jugador alcanza 10 puntos, anuncia su total y reclama la victoria en este juego galardonado y muy popular.",
  },
  {
    id: 478,
    nombre: "Citadels",
    precio: 24.73,
    img: "./images/478.webp",
    stock: 3,
    ano: 2000,
    minjug: 2,
    maxjug: 8,
    tiempo: 60,
    raiting: 7.08089,
    BGGrank: 403,
    complejidad: 2.053,
    categoria: ["Family Games", "Strategy Games"],
    descripcion:
      "En Citadels, los jugadores asumen nuevos roles en cada ronda para representar personajes que contratan con el objetivo de adquirir oro y construir edificios. El juego finaliza al concluir una ronda en la que un jugador construye su octavo edificio. Los jugadores entonces suman sus puntos, y el jugador con la puntuación más alta gana. Comienzan con cartas de edificios en su mano, y al principio de cada ronda, el jugador que fue rey en la ronda anterior descarta una de las ocho cartas de personaje al azar y elige una, pasando las cartas al siguiente jugador, y así sucesivamente. Cada personaje tiene una habilidad especial, y la utilidad de cada personaje depende de la situación, tanto propia como de los oponentes. Los personajes llevan a cabo sus acciones en orden numérico, realizando diversas acciones como asesinar a otro personaje, robar oro, intercambiar cartas de edificios y destruir edificios. El juego combina estrategia y toma de decisiones tácticas mientras los jugadores compiten por construir edificios y acumular puntos para la victoria.",
  },
  {
    id: 297030,
    nombre: "Tekhenu: Obelisk of the Sun",
    precio: 45,
    img: "./images/297030.webp",
    stock: 3,
    ano: 2020,
    minjug: 1,
    maxjug: 4,
    tiempo: 120,
    raiting: 7.9575,
    BGGrank: 452,
    complejidad: 4.0093,
    categoria: ["Strategy Games"],
    descripcion:
      "En Tekhenu: Obelisk of the Sun, los jugadores se sumergen en la construcción y expansión del Templo de Amón-Ra en Karnak, Egipto, honrando a los dioses mediante la gestión estratégica de acciones. El tablero, dividido en secciones asociadas con dioses egipcios, y un imponente obelisco que proyecta sombras, crea desafíos tácticos. Durante varias rondas, los jugadores seleccionan dados, realizan acciones divinas y equilibran pureza y contaminación. Las fases de puntuación premian la construcción y la felicidad del pueblo. La cuidadosa planificación y adaptación a las sombras del obelisco son clave para obtener la victoria en este juego de gestión y estrategia.",
  },
];

export const getProductos = () => {
  return new Promise((respuesta) => {
    setTimeout(() => {
      respuesta(productos);
    }, 2000);
  });
};

// Función de un solo item

export const getUnProducto = (id) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const producto = productos.find((prod) => prod.id === id);
      resolve(producto);
    }, 2000);
  });
};
